---
title: "ClimMani Paper Affiliations"
author: "Aud Halbritter"
date: "3 8 2018"
output: word_document
---

#```{r setup, include=FALSE}
#knitr::read_chunk("Affiliation.R")
#```



AFFILIATION LIST

^1^Centre for Environmental and Marine Studies (CESAM), Department of Environment and Planning, University of Aveiro, Aveiro, Portugal, ^2^BC3-Basque Centre for Climate Change, University of the Basque Country, Leioa, Spain, ^3^Department of Biological Sciences and Bjerknes Centre for Climate Research, University of Bergen, Bergen, Norway, ^4^Department of Natural Resources and Environmental Sciences, Agricultural University of Iceland, Reykjav<U+00ED>k, Iceland, ^5^Environmental Sciences, Copernicus Institute of Sustainable Development, Utrecht University, Utrecht, the Netherlands, ^6^Department of Geosciences and Natural Resource Management, University of Copenhagen, Frederiksberg, Denmark, ^7^Experimental Plant Ecology, Institute of Botany and Landscape Ecology, University of Greifswald, Greifswald, Germany, ^8^Department of Forest Sciences, University of Helsinki, Helsinki, Finland, ^9^Section of Biology, University of G<U+00E4>vle, G<U+00E4>vle, Sweden, ^10^Schmid College of Science and Technology, Chapman University, Orange, USA, ^11^Faculty of Environmental Sciences and Natural Resource Management, Norwegian University of Life Sciences, <U+00C5>s, Norway, ^12^Environmental Change Institute, School of Geography and the Environment, University of Oxford, Oxford, UK, ^13^School of Life Sciences, Arizona State University, Tempe, USA, ^14^Department of Civil, Environmental, and Geodetic Engineering, Ohio State University, USA, ^15^College of Science and Engineering, James Cook University, Cairns, Queensland, Australia, ^16^Meteorology Department, Pozna<U+0144> University of Life Sciences,  Pozna<U+0144>, Poland, ^17^Centre for Ecology & Hydrology, Environment Centre Wales, Bangor, UK, ^18^Earth and Environmental Sciences Division, Los Alamos National Laboratory, Los Alamos, USA, ^19^Swiss Federal Institute for Forest, Snow and Landscape Research (WSL), Birmensdorf, Switzerland, ^20^CREAF, Cerdanyola del Vall<U+00E8>s, Spain, ^21^CSIC, Global Ecology Unit CREAF-CSIC-UAB, Bellaterra, Spain, ^22^Centre of Excellence PLECO (Plants and Ecosystems), Biology Department, University of Antwerp, Wilrijk, Belgium, ^23^Department of Environmental Sciences, Western Norway University of Applied Sciences, Sogndal, Norway, ^24^Department of Biology, Virginia Commonwealth University, Richmond, USA, ^25^Department of Biology, University of North Carolina, Chapel Hill, USA, ^26^Department of Environmental Sciences <U+2013> Botany, University of Basel, Basel, Switzerland, ^27^Global Change Research Institute, The Czech Academy of Sciences, Brno, Czech Republic, ^28^Warnell School of Forestry and Natural Resources, University of Georgia, Athens, USA, ^29^Department of Plants, Soils and Climate, Utah State University, Logan, USA, ^30^Department of Forest Ecology and Management, Swedish University of Agricultural Sciences, Ume<U+00E5>, Sweden, ^31^Faculty of AgriSciences, Mendel University in Brno, Brno, Czech Republic, ^32^The Science Library, University of Oslo, Norway, ^33^Institute of Ecology and Botany, MTA Centre for Ecological Research, V<U+00E1>cr<U+00E1>t<U+00F3>t, Hungary, ^34^Department of Renewable Resources, University of Alberta, Edmonton, Canada, ^35^Forest Dynamics, Swiss Federal Institute for Forest, Snow and Landscape Research WSL, Birmensdorf, Switzerland, ^36^Clinical Trial Unit Bern, Department of Clinical Research, University of Bern, Bern, Switzerland, ^37^Institute of Crop Science and Resource Conservation (INRES), University of Bonn, Bonn, Germany, ^38^Range Ecology and Management Group, Botanical Institute, University of Cologne, Cologne, Germany, ^39^Institute of Ecology and Earth Sciences, University of Tartu, Tartu, Estonia, ^40^Bangor University School of Natural Sciences, Bangor, UK, ^41^Department of Geological Sciences, Jackson School of Geosciences, The University of Texas at Austin, Austin, USA, ^42^Pacific Northwest National Laboratory, Richland, USA, ^43^Plant Ecology, Albrecht von Haller Institute for Plant Sciences, Plant Ecology and Ecosystems Research, University of Goettingen, Goettingen, Germany, ^44^Pacific Northwest Research Station, USDA Forest Service, Corvallis, USA, ^45^Biosphere 2 and Department of Ecology & Evolutionary Biology, University of Arizona, Tucson, USA, ^46^Department of Botany and Biodiversity Research Centre, University of British Columbia, Vancouver, Canada, ^47^College of Natural Resources, University of Idaho, Moscow, USA, ^48^Optics of Photosynthesis Laboratory, Institute for Atmospheric and Earth System Research/Forest Sciences, University of Helsinki, Helsinki, Finland, ^49^AXA Chair Programme in Biosphere and Climate Impacts, Department of Life Sciences, Imperial College London, Ascot, UK, ^50^Norwegian Polar Institute, Fram Centre, Troms<U+00F8>, Norway, ^51^Biology and Geology Departments, Lawrence University, Appleton, USA, ^52^Institute of Evolution and Ecology, Plant Ecology Group, University of T<U+00FC>bingen, T<U+00FC>bingen, Germany, ^53^Department of Ecology and Evolutionary Biology, University of California Los Angeles, Los Angeles, USA, ^54^Department of Forest Ecology and Soils, Federal Research and Training Centre for Forests, Natural Hazards and Landscape, Vienna, Austria, ^55^Department of Biological Sciences, California State University, Los Angeles, Los Angeles, USA, ^56^Centre for Ecology & Hydrology, Environment Centre Lancaster, Lancaster University, Lancaster, UK, ^57^Department of Biology, Norwegian University of Science and Technology, Trondheim, Norway, ^58^Department of Ecology and Evolutionary Biology, Cornell University, Ithaca, USA, ^59^Department of Natural History, NTNU University Museum, Norwegian University of Science and Technology, Trondheim, Norway, ^60^Norwegian Institute for Nature Research, Oslo, Norway, ^61^Department of Biological Sciences, University of Bergen, Bergen, Norway, ^62^Norwegian Institute for Nature Research, Bergen, Norway, ^63^Department of Agroecology, Aarhus University, Tjele, Denmark, ^64^Section for Genetics and Evolutionary Biology (EVOGENE), Department of Biosciences, University of Oslo, Oslo, Norway, ^65^Interdisciplinary Environmental Research Centre, Technische Universit<U+00E4>t Bergakademie Freiberg, Germany, ^66^Soil Physics and Land Management, Wageningen University, Wageningen, the Netherlands


NAME LIST

Nelson Abrantes^1^, Mar<U+00ED>a Almagro^2^, Inge H. J. Althuizen^3^, Isabel C. Barrio^4^, Mariska te Beest^5^, Claus Beier^6^, Ilka Beil^7^, Bj<U+00F6>rn Berg^8,9^, Z. Carter Berry^10^, Tone Birkemoe^11^, Benjamin Blonder^12,13^, Gesche Blume-Werry^7^, Gil Bohrer^14^, Isabel Campos^1^, Lucas A. Cernusak^15^, Bogdan H. Chojnicki^16^, Bernhard J. Cosby^17^, Lee T. Dickman^18^, Ika Djukic^19^, Iolanda Filella^20,21^, Lucia Fuchslueger^22^, Albert Gargallo-Garriga^21^, Mark A. K. Gillespie^23^, Gregory R. Goldsmith^10^, Christopher Gough^24^, Fletcher W. Halliday^25^, Stein Joar Hegland^23^, G<U+00FC>nter Hoch^26^, Petr Holub^27^, Francesca Jaroszynska^3^, Daniel M. Johnson^28^, Scott B. Jones^29^, Paul Kardol^30^, Jan J. Keizer^1^, Karel Klem^31^, Heidi S. Konestabo^32^, Gy<U+00F6>rgy Kr<U+00F6>el-Dulay^33^, J<U+00FC>rgen Kreyling^7^, Simon M. Landh<U+00E4>usser^34^, Klaus S. Larsen^6^, Niki Leblans^22^, Inma Lebron^17^, Marco M. Lehmann^35^, Jonas J. Lembrechts^22^, Armando Lenz^36^, Anja Linst<U+00E4>dter^37,38^, Joan Llusi<U+00E0>^21^, Pille M<U+00E4>nd^39^, Andrey V. Malyshev^7^, Miles Marshall^40^, Ashley M. Matheny^41^, Nate McDowell^42^, Ina C. Meier^43^, Frederick C. Meinzer^44^, Sean T. Michaletz^45,46,18^, Megan L. Miller^47^, Lena Muffler^7,43^, Michal Oravec^27^, Ivika Ostonen^39^, Albert Porcar-Castell^48^, Catherine Preece^20,21^, Iain C. Prentice^49^, Dajana Radujkovi<U+0107>^22^, Virve Ravolainen^50^, Relena Ribbons^51^, Jan C. Ruppert^52^, Lawren Sack^53^, Jordi Sardans^20,21^, Andreas Schindlbacher^54^, Christine Scoffoni^55^, Bjarni D. Sigurdsson^4^, Simon Smart^56^, Stuart Smith^57^, Fiona Soper^58^, James D. M. Speed^59^, Anne Sverdrup-Thygeson^11^, Markus A. K. Sydenham^60^, Joachim P. T<U+00F6>pper^61,62^, Arezoo Taghizadeh-Toosi^63^, Richard J. Telford^3^, Katja Tielb<U+00F6>rger^52^, Otmar Urban^27^, Leandro Van Langenhove^22^, Krist<U+00FD>na Ve<U+010D>e<U+0159>ov<U+00E1>^27^, Arne Ven^22^, Erik Verbruggen^22^, Unni Vik^64^, Robert Weigel^43^, Thomas Wohlgemuth^35^, Lauren K. Wood^24^, Julie Zinnert^24^, Kamal Zurba^65^, Martine van der Ploeg^66^